# Generated by Django 4.1.6 on 2025-12-18 19:21

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0003_school_official_levels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_usermergerequest_confirmations_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('html_message', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='HTML мессеж')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('from_email', models.CharField(choices=[('baysa@mmo.mn', 'baysa@mmo.mn'), ('baysa@integral.mn', 'baysa@integral.mn'), ('baysa@mathminds.club', 'baysa@mathminds.club'), ('info@mmo.mn', 'info@mmo.mn'), ('registration@mmo.mn', 'registration@mmo.mn')], default='baysa@mmo.mn', max_length=255, verbose_name='Илгээгч имэйл хаяг')),
                ('is_tested', models.BooleanField(default=False, verbose_name='Тест илгээсэн эсэх')),
                ('test_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Тест илгээсэн огноо')),
                ('test_recipient_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Тест имэйл хаяг')),
                ('filter_active_year', models.BooleanField(default=False, verbose_name='Сүүлийн жилд нэвтэрсэн')),
                ('filter_teachers', models.BooleanField(default=False, verbose_name='Багш нар')),
                ('filter_students', models.BooleanField(default=False, verbose_name='Сурагчид')),
                ('filter_school_managers', models.BooleanField(default=False, verbose_name='Сургуулийн менежер')),
                ('use_custom_list', models.BooleanField(default=False, verbose_name='Custom имэйл жагсаалт')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('paused', 'Paused')], default='draft', max_length=20)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('daily_limit', models.IntegerField(default=50000)),
                ('emails_sent_today', models.IntegerField(default=0)),
                ('last_reset_date', models.DateField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specific_province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.province', verbose_name='Аймаг')),
                ('specific_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school', verbose_name='Сургууль')),
            ],
        ),
        migrations.CreateModel(
            name='EmailUnsubscribe',
            fields=[
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('unsubscribed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('is_test', models.BooleanField(blank=True, default=False, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='emails.emailcampaign')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailBounce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('bounce_type', models.CharField(choices=[('hard', 'Hard Bounce'), ('soft', 'Soft Bounce'), ('complaint', 'Complaint')], max_length=20)),
                ('message_id', models.CharField(blank=True, max_length=255)),
                ('notification_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='emails.emailrecipient')),
            ],
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['campaign', 'status'], name='emails_emai_campaig_e2e9a6_idx'),
        ),
        migrations.AddIndex(
            model_name='emailrecipient',
            index=models.Index(fields=['status', 'sent_at'], name='emails_emai_status_86733b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='emailrecipient',
            unique_together={('campaign', 'user')},
        ),
        migrations.AddIndex(
            model_name='emailbounce',
            index=models.Index(fields=['email', 'bounce_type'], name='emails_emai_email_c88681_idx'),
        ),
    ]
