# Generated by Django 4.1.6 on 2026-02-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='unique_per_email',
            field=models.BooleanField(default=True, help_text='Үнэн бол нэг имэйл хаяг руу зөвхөн 1 удаа илгээнэ. Худал бол хэрэглэгч бүрт илгээнэ (ижил имэйлтэй хэрэглэгчид бүгдэд явна).', verbose_name='Нэг имэйл рүү 1 удаа'),
        ),
    ]
