# Generated by Django 5.2.7 on 2026-10-01 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_fix_user_fk_cascade_constraints'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(db_index=True, max_length=255)),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('event_type', models.CharField(choices=[('delivery', 'Хүргэгдсэн'), ('open', 'Нээсэн'), ('click', 'Холбоос дарсан')], max_length=20)),
                ('occurred_at', models.DateTimeField()),
                ('link', models.URLField(blank=True, max_length=2000)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['message_id', 'event_type'], name='emails_emai_message_6d2de5_idx')],
            },
        ),
    ]
