# Generated by Django 4.1.6 on 2025-12-16 22:58

import ckeditor_uploader.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
        ('olympiad', '0005_problem_numerical_answer2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldid', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('descr', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('imagesource', models.CharField(blank=True, max_length=200, null=True)),
                ('isspec', models.BooleanField(default=True)),
                ('embedcode', models.TextField(blank=True, null=True)),
                ('pictures', models.TextField(blank=True, null=True)),
                ('files', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('sawcount', models.IntegerField(blank=True, null=True)),
                ('isshow', models.BooleanField(default=True)),
                ('createuserid', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateField(auto_now_add=True, null=True)),
                ('updatedate', models.DateField(auto_now=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.author')),
                ('year', models.ForeignKey(blank=True, default=posts.models.get_current_school_year, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.schoolyear')),
            ],
            options={
                'ordering': ['-year_id', '-isspec'],
            },
        ),
    ]
