# Generated by Django 4.1.6 on 2025-09-11 12:22

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('olympiad', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oldid', models.IntegerField(default=1)),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('intro', models.TextField(blank=True, null=True)),
                ('descr', ckeditor.fields.RichTextField(blank=True, null=True)),
                ('startdate', models.DateField(blank=True, null=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('imagesource', models.CharField(blank=True, max_length=200, null=True)),
                ('isspec', models.BooleanField(default=True)),
                ('embedcode', models.TextField(blank=True, null=True)),
                ('pictures', models.TextField(blank=True, null=True)),
                ('files', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('sawcount', models.IntegerField(blank=True, null=True)),
                ('isshow', models.BooleanField(default=True)),
                ('createuserid', models.IntegerField(blank=True, null=True)),
                ('createdate', models.DateField(blank=True, null=True)),
                ('updatedate', models.DateField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.author')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.schoolyear')),
            ],
            options={
                'ordering': ['-year_id', '-isspec'],
            },
        ),
    ]
