# Generated by Django 4.1.6 on 2025-12-18 14:06
# Note: Like and Notification models never existed in the database, so this is a no-op

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_like_notification'),
    ]

    operations = [
        # No operations needed - Like and Notification were never created
    ]
