# Generated by Django 5.2.7 on 2026-07-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0001_initial'),
        ('posts', '0003_remove_notification_actor_remove_notification_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='attachments',
            field=models.ManyToManyField(blank=True, related_name='posts', to='file_management.fileupload'),
        ),
    ]
