from django.urls import path
from . import views

urlpatterns = [
    path('', views.my_managed_provinces, name='my_managed_provinces'),
    path('<int:province_id>/', views.province_dashboard, name='province_dashboard'),
    path('<int:province_id>/change-contact/', views.province_change_contact, name='province_change_contact'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/',
         views.province_olympiad_view, name='province_olympiad_view'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/add-by-threshold/',
         views.add_students_by_threshold, name='add_students_by_threshold'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/select-top-students/',
         views.select_top_students_by_school, name='select_top_students_by_school'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/add-by-id/',
         views.add_students_by_id, name='add_students_by_id'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/generate-sheet/',
         views.generate_province_answer_sheet, name='generate_province_answer_sheet'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/import-sheet/',
         views.import_province_answer_sheet, name='import_province_answer_sheet'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/results/',
         views.view_province_olympiad_results, name='view_province_olympiad_results'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/round1-results/',
         views.view_round1_province_results, name='view_round1_province_results'),
    path('<int:province_id>/olympiad/<int:olympiad_id>/participants/',
         views.view_province_participants, name='view_province_participants'),

    # Zone (Бүс) level URLs - Round 3
    path('zones/', views.my_managed_zones, name='my_managed_zones'),
    path('zones/<int:zone_id>/', views.zone_dashboard, name='zone_dashboard'),
    path('zones/<int:zone_id>/change-contact/', views.zone_change_contact, name='zone_change_contact'),
    path('zones/<int:zone_id>/select-olympiads/', views.zone_select_olympiads, name='zone_select_olympiads'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/',
         views.zone_olympiad_view, name='zone_olympiad_view'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/add-all-qualified/',
         views.zone_add_all_qualified, name='zone_add_all_qualified'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/add-by-threshold/',
         views.zone_add_students_by_threshold, name='zone_add_students_by_threshold'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/select-top-students/',
         views.zone_select_top_students, name='zone_select_top_students'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/add-by-id/',
         views.zone_add_students_by_id, name='zone_add_students_by_id'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/generate-sheet/',
         views.zone_generate_answer_sheet, name='zone_generate_answer_sheet'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/import-sheet/',
         views.zone_import_answer_sheet, name='zone_import_answer_sheet'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/results/',
         views.zone_view_results, name='zone_view_results'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/round2-results/',
         views.zone_view_round2_results, name='zone_view_round2_results'),
    path('zones/<int:zone_id>/olympiad/<int:olympiad_id>/participants/',
         views.zone_view_participants, name='zone_view_participants'),
]
