# Generated by Django 4.1.6 on 2024-10-27 06:41

import accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='is_author', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('contact_person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': [('edit_province', 'Аймаг дүүргийн мэдээлэл оруулах')],
            },
        ),
        migrations.CreateModel(
            name='UserMails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('text_html', models.TextField(default='')),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('replyto_email', models.EmailField(default='baysa.edu@gmail.com', max_length=254)),
                ('bcc', models.TextField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_opened', models.BooleanField(default=False)),
                ('tracking_token', models.UUIDField(default=uuid.uuid4, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': [('edit_province', 'Аймаг дүүргийн мэдээлэл оруулах')],
            },
        ),
        migrations.CreateModel(
            name='UserMeta',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='data', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('photo', models.ImageField(blank=True, upload_to=accounts.models.user_directory_path)),
                ('reg_num', models.CharField(max_length=12)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(choices=[('Эр', 'Эрэгтэй'), ('Эм', 'Эмэгтэй')], default='', max_length=2)),
                ('address1', models.CharField(blank=True, max_length=240, null=True)),
                ('address2', models.CharField(blank=True, max_length=240, null=True)),
                ('mobile', models.IntegerField(null=True)),
                ('is_valid', models.BooleanField(default=False)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.grade')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.level')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.province')),
            ],
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_started', models.DateField(auto_now=True)),
                ('date_finished', models.DateField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.province')),
            ],
            options={
                'permissions': [('edit_school', 'Сургуулийн мэдээлэл оруулах')],
            },
        ),
        migrations.AddField(
            model_name='province',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.zone'),
        ),
        migrations.AddIndex(
            model_name='usermeta',
            index=models.Index(fields=['school'], name='accounts_us_school_a59d10_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeta',
            index=models.Index(fields=['reg_num'], name='accounts_us_reg_num_376acb_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeta',
            index=models.Index(fields=['mobile'], name='accounts_us_mobile_28b4b2_idx'),
        ),
    ]
