# Generated by Django 5.2.8 on 2025-11-21 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schools.school'),
        ),
        migrations.AddField(
            model_name='province',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.zone'),
        ),
        migrations.AddIndex(
            model_name='usermeta',
            index=models.Index(fields=['reg_num'], name='accounts_us_reg_num_376acb_idx'),
        ),
        migrations.AddIndex(
            model_name='usermeta',
            index=models.Index(fields=['mobile'], name='accounts_us_mobile_28b4b2_idx'),
        ),
    ]
