# Generated by Django 4.1.6 on 2025-12-18 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMergeRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ids', models.JSONField(help_text='JSON array: [101, 205, 308]', verbose_name='Нэгтгэх хэрэглэгчдийн ID')),
                ('reason', models.TextField(blank=True, help_text='Яагаад эдгээр хэрэглэгчдийг нэгтгэх шаардлагатай вэ?', verbose_name='Шалтгаан/Тайлбар')),
                ('status', models.CharField(choices=[('pending', 'Хүлээгдэж буй'), ('approved', 'Зөвшөөрсөн'), ('rejected', 'Татгалзсан'), ('completed', 'Дууссан'), ('failed', 'Амжилтгүй')], default='pending', max_length=20, verbose_name='Төлөв')),
                ('has_conflicts', models.BooleanField(default=False, verbose_name='Зөрчил байгаа эсэх')),
                ('conflicts_data', models.JSONField(blank=True, help_text='Дүнгийн давхцал, өгөгдлийн зөрчил зэрэг', null=True, verbose_name='Зөрчлийн дэлгэрэнгүй')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Хянасан огноо')),
                ('review_notes', models.TextField(blank=True, verbose_name='Хянасан тэмдэглэл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Үүсгэсэн огноо')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Шинэчилсэн огноо')),
                ('merge_error', models.TextField(blank=True, verbose_name='Нэгтгэх алдаа')),
                ('primary_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_as_primary', to=settings.AUTH_USER_MODEL, verbose_name='Үндсэн хэрэглэгч')),
                ('requesting_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='merge_requests_created', to=settings.AUTH_USER_MODEL, verbose_name='Хүсэлт үүсгэсэн хэрэглэгч')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merge_requests_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='Хянасан хэрэглэгч')),
            ],
            options={
                'verbose_name': 'Хэрэглэгч нэгтгэх хүсэлт',
                'verbose_name_plural': 'Хэрэглэгч нэгтгэх хүсэлтүүд',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='usermergerequest',
            index=models.Index(fields=['status', 'created_at'], name='accounts_us_status_0fc8a7_idx'),
        ),
        migrations.AddIndex(
            model_name='usermergerequest',
            index=models.Index(fields=['requesting_user', 'status'], name='accounts_us_request_f1fe65_idx'),
        ),
    ]
