# Generated by Django 4.1.6 on 2025-12-18 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_usermergerequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermergerequest',
            name='confirmations',
            field=models.JSONField(default=dict, help_text="Format: {user_id: {status: 'pending/confirmed/rejected', token: 'uuid', confirmed_at: timestamp}}", verbose_name='Хэрэглэгчдийн баталгаажуулалт'),
        ),
        migrations.AddField(
            model_name='usermergerequest',
            name='requires_user_confirmation',
            field=models.BooleanField(default=True, verbose_name='Хэрэглэгчдээс баталгаажуулалт шаардах эсэх'),
        ),
    ]
