# Generated by Django 4.1.6 on 2026-02-13 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0004_usermergerequest_confirmations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_zones', to=settings.AUTH_USER_MODEL),
        ),
    ]
