# Generated by Django 4.1.6 on 2026-02-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0005_problem_numerical_answer2'),
        ('accounts', '0005_add_zone_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='olympiads',
            field=models.ManyToManyField(blank=True, related_name='zones', to='olympiad.olympiad'),
        ),
    ]
