# Generated by Django 5.2.7 on 2026-08-24 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fix_user_fk_cascade_constraints'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='registrar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registering_provinces', to=settings.AUTH_USER_MODEL, verbose_name='Бүртгэгч багш'),
        ),
        migrations.AlterField(
            model_name='province',
            name='contact_person',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Аймгийн удирдах ажилтан'),
        ),
    ]
