# Generated by Django 5.2.7 on 2026-09-28 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_province_registrar_alter_province_contact_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermeta',
            name='last_activity',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
