# Generated by Django 5.2.7 on 2026-10-01 13:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_usermeta_last_activity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='province',
            name='contact_person2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='second_contact_provinces', to=settings.AUTH_USER_MODEL, verbose_name='Аймгийн удирдах ажилтан 2'),
        ),
    ]
