# Generated by Django 3.1.6 on 2021-10-27 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210401_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=256)),
                ('text', models.TextField()),
                ('from_email', models.EmailField(max_length=254)),
                ('to_email', models.EmailField(max_length=254)),
                ('is_sent', models.BooleanField(default=False)),
            ],
        ),
    ]
