# Generated by Django 3.1.6 on 2022-02-17 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220131_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, null=True)),
                ('description', models.TextField()),
            ],
            options={
                'permissions': [('edit_province', 'Аймаг дүүргийн мэдээлэл оруулах')],
            },
        ),
        migrations.AddField(
            model_name='province',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.zone'),
        ),
    ]
