# Generated by Django 3.1.6 on 2023-02-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220218_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermails',
            name='bcc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='usermails',
            name='replyto_email',
            field=models.EmailField(default='baysa.edu@gmail.com', max_length=254),
        ),
        migrations.AddField(
            model_name='usermails',
            name='text_html',
            field=models.TextField(default=''),
        ),
    ]
