# Generated by Django 5.2.8 on 2025-11-21 16:04

import django.db.models.deletion
import olympiad.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=10, null=True)),
                ('start', models.DateField(blank=True, null=True)),
                ('end', models.DateField(blank=True, null=True)),
                ('descr', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(null=True)),
            ],
            options={
                'permissions': [('edit_solution', 'Can edit solution')],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('ALG', 'Алгебр'), ('COM', 'Комбинаторик'), ('GEO', 'Геометр'), ('NUM', 'Тооны онол'), ('MIX', 'Хольмог')], default='ALG', max_length=3)),
                ('name', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_time', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('is_accepted', models.BooleanField(default=True)),
                ('is_supplement', models.BooleanField(default=False)),
                ('file', models.ImageField(upload_to=olympiad.models.Upload.file_to)),
            ],
        ),
        migrations.CreateModel(
            name='Olympiad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(default='')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('final_message', models.TextField(default='Бодлогууд таалагдсан гэдэгт итгэлтэй байна. Цаашид улам хичээн суралцаарай!')),
                ('is_open', models.BooleanField(default=True)),
                ('is_grading', models.BooleanField(default=False)),
                ('round', models.IntegerField(choices=[(0, 'Бусад олимпиад'), (1, 'Сургуулийн олимпиад'), (2, 'Аймаг/Дүүргийн олимпиад'), (3, 'Нийслэл/Бүсийн олимпиад'), (4, 'Улсын олимпиад'), (5, 'Олон улсын олимпиад'), (6, 'Олон улсын бусад'), (7, 'Сонгон шалгаруулалт')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'Уламжлалт'), (1, 'Тест')], default=0)),
                ('month', models.IntegerField(blank=True, null=True)),
                ('num', models.IntegerField(default=1)),
                ('json_results', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.province')),
                ('level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.level')),
                ('next_round', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='olympiad.olympiad')),
                ('school_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.schoolyear')),
            ],
            options={
                'ordering': ['-school_year_id', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(choices=[('Алт', 'Алтан медаль'), ('Мөнгө', 'Мөнгөн медаль'), ('Хүрэл', 'Хүрэл медаль'), ('Тусгай', 'Тусгай шагнал'), ('Уран бодолт', 'Уран бодолт'), ('I шат', 'I шат'), ('II шат', 'II шат')], default='Алт', max_length=128)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_awards', to=settings.AUTH_USER_MODEL)),
                ('contestant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='awards', to='accounts.grade')),
                ('olympiad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='olympiad.olympiad')),
            ],
            options={
                'permissions': [('edit_award', 'Шагнал засах'), ('confirm_award', 'Шагнал баталгаажуулах')],
            },
        ),
        migrations.CreateModel(
            name='OlympiadGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group')),
                ('olympiads', models.ManyToManyField(blank=True, to='olympiad.olympiad')),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('statement', models.TextField(blank=True, null=True)),
                ('max_score', models.IntegerField(default=7)),
                ('state', models.IntegerField(choices=[(0, 'Дэвшигдсэн'), (1, 'Сонгогдсон')], default=0)),
                ('type', models.IntegerField(choices=[(0, 'Уламжлалт'), (1, 'Сонгох'), (2, 'Нөхөх')], default=0)),
                ('numerical_answer', models.BigIntegerField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.author')),
                ('olympiad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.olympiad')),
            ],
            options={
                'permissions': [('edit_problem', 'Can edit problem')],
            },
        ),
        migrations.CreateModel(
            name='AnswerChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('label', models.CharField(max_length=8)),
                ('value', models.TextField(default='')),
                ('points', models.IntegerField()),
                ('problem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olympiad.problem')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_grade', models.IntegerField(default=0)),
                ('answer', models.BigIntegerField(blank=True, null=True)),
                ('score', models.FloatField(blank=True, null=True)),
                ('grader_comment', models.TextField(blank=True, default='')),
                ('source_file', models.TextField(blank=True, default='')),
                ('state', models.IntegerField(choices=[(0, 'Хариулаагүй'), (1, 'Засагдаагүй'), (2, 'Урьдчилсан'), (3, 'Маргаантай'), (4, 'Зөвшөөрөгдсөн'), (5, 'Батлагдсан')], default=0)),
                ('date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=False)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_results', to=settings.AUTH_USER_MODEL)),
                ('contestant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contest_results', to=settings.AUTH_USER_MODEL)),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_results', to=settings.AUTH_USER_MODEL)),
                ('olympiad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.olympiad')),
                ('problem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olympiad.problem')),
            ],
            options={
                'permissions': [('edit_result', 'Дүн оруулах'), ('confirm_result', 'Дүн баталгаажуулах')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('recommendation', models.FloatField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='olympiad.result')),
            ],
        ),
        migrations.CreateModel(
            name='ScoreSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.FloatField(blank=True, default=0, null=True)),
                ('s2', models.FloatField(blank=True, default=0, null=True)),
                ('s3', models.FloatField(blank=True, default=0, null=True)),
                ('s4', models.FloatField(blank=True, default=0, null=True)),
                ('s5', models.FloatField(blank=True, default=0, null=True)),
                ('s6', models.FloatField(blank=True, default=0, null=True)),
                ('s7', models.FloatField(blank=True, default=0, null=True)),
                ('s8', models.FloatField(blank=True, default=0, null=True)),
                ('s9', models.FloatField(blank=True, default=0, null=True)),
                ('s10', models.FloatField(blank=True, default=0, null=True)),
                ('s11', models.FloatField(blank=True, default=0, null=True)),
                ('s12', models.FloatField(blank=True, default=0, null=True)),
                ('s13', models.FloatField(blank=True, default=0, null=True)),
                ('s14', models.FloatField(blank=True, default=0, null=True)),
                ('s15', models.FloatField(blank=True, default=0, null=True)),
                ('s16', models.FloatField(blank=True, default=0, null=True)),
                ('s17', models.FloatField(blank=True, default=0, null=True)),
                ('s18', models.FloatField(blank=True, default=0, null=True)),
                ('s19', models.FloatField(blank=True, default=0, null=True)),
                ('s20', models.FloatField(blank=True, default=0, null=True)),
                ('list_rank', models.IntegerField(default=0)),
                ('ranking_a', models.IntegerField(default=0)),
                ('ranking_b', models.IntegerField(default=0)),
                ('list_rank_p', models.IntegerField(default=0)),
                ('ranking_a_p', models.IntegerField(default=0)),
                ('ranking_b_p', models.IntegerField(default=0)),
                ('list_rank_z', models.IntegerField(default=0)),
                ('ranking_a_z', models.IntegerField(default=0)),
                ('ranking_b_z', models.IntegerField(default=0)),
                ('prizes', models.CharField(blank=True, max_length=512, null=True)),
                ('total', models.FloatField(blank=True, default=0, null=True)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_sheets', to='olympiad.olympiad')),
            ],
        ),
    ]
