# Generated by Django 3.1.6 on 2022-01-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='olympiad',
            name='is_grading',
            field=models.BooleanField(default=False),
        ),
    ]
