# Generated by Django 4.1.6 on 2025-02-08 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='list_rank',
            field=models.IntegerField(default=0),
        ),
    ]
