# Generated by Django 4.1.6 on 2025-02-08 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0002_scoresheet_list_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='list_rank_p',
            field=models.IntegerField(default=0),
        ),
    ]
