# Generated by Django 4.1.6 on 2024-11-28 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0002_alter_olympiad_round'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='isspec',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='oldid',
            field=models.IntegerField(default=1),
        ),
    ]
