# Generated by Django 5.0.6 on 2024-05-25 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0002_olympiad_json_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-year_id', '-isspec']},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='CreateDate',
            new_name='createdate',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='CreateUserId',
            new_name='createuserid',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Descr',
            new_name='descr',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='EmbedCode',
            new_name='embedcode',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='EndDate',
            new_name='enddate',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Files',
            new_name='files',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='ImageSource',
            new_name='imagesource',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Intro',
            new_name='intro',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='IsShow',
            new_name='isshow',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='IsSpec',
            new_name='isspec',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='OldId',
            new_name='oldid',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Pictures',
            new_name='pictures',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='SawCount',
            new_name='sawcount',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='StartDate',
            new_name='startdate',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='Tags',
            new_name='tags',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='UpdateDate',
            new_name='updatedate',
        ),
        migrations.AlterField(
            model_name='award',
            name='place',
            field=models.CharField(choices=[('Алт', 'Алтан медаль'), ('Мөнгө', 'Мөнгөн медаль'), ('Хүрэл', 'Хүрэл медаль'), ('Тусгай', 'Тусгай шагнал'), ('Уран бодолт', 'Уран бодолт'), ('I шат', 'I шат'), ('II шат', 'II шат')], default='Алт', max_length=128),
        ),
    ]
