# Generated by Django 3.1.6 on 2022-01-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0002_auto_20220130_2320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiad',
            options={'ordering': ['-school_year_id', '-level', 'round', 'id']},
        ),
        migrations.AlterField(
            model_name='olympiad',
            name='final_message',
            field=models.TextField(default='Бодлогууд таалагдсан гэдэгт итгэлтэй байна. Цаашид улам хичээн суралцаарай!'),
        ),
    ]
