# Generated by Django 4.1.6 on 2024-08-27 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0002_olympiad_json_results'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='place',
            field=models.CharField(choices=[('Алт', 'Алтан медаль'), ('Мөнгө', 'Мөнгөн медаль'), ('Хүрэл', 'Хүрэл медаль'), ('Тусгай', 'Тусгай шагнал'), ('Уран бодолт', 'Уран бодолт'), ('I шат', 'I шат'), ('II шат', 'II шат')], default='Алт', max_length=128),
        ),
    ]
