# Generated by Django 5.2.8 on 2025-11-21 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='is_official',
            field=models.BooleanField(default=False),
        ),
    ]
