# Generated by Django 4.1.6 on 2025-02-09 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0003_scoresheet_list_rank_p'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='list_rank_z',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_a_z',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_b_z',
            field=models.IntegerField(default=0),
        ),
    ]
