# Generated by Django 5.0.6 on 2024-05-25 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0003_alter_article_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='Author',
            new_name='author',
        ),
    ]
