# Generated by Django 4.1.6 on 2024-11-28 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0003_alter_article_isspec_alter_article_oldid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='createdate',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='article',
            name='startdate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
