# Generated by Django 4.1.6 on 2023-12-20 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0003_olympidgroup_delete_yourmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OlympidGroup',
            new_name='OlympiadGroup',
        ),
    ]
