# Generated by Django 5.2.8 on 2025-11-24 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0003_add_is_official_to_scoresheet'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='list_rank_p_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='list_rank_p_u',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='list_rank_z_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='list_rank_z_u',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_a_p_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_a_p_u',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_a_z_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_a_z_u',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_b_p_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_b_p_u',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_b_z_all',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_b_z_u',
            field=models.IntegerField(default=0),
        ),
    ]
