# Generated by Django 3.1.6 on 2022-01-31 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20220131_1816'),
        ('olympiad', '0003_auto_20220131_0101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiad',
            options={'ordering': ['-school_year_id', 'level', 'round', 'id']},
        ),
        migrations.AlterModelOptions(
            name='schoolyear',
            options={'ordering': ['-name']},
        ),
        migrations.AlterField(
            model_name='problem',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.author'),
        ),
    ]
