# Generated by Django 4.1.6 on 2024-09-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0003_alter_award_place'),
        ('olympiad', '0004_rename_author_article_author'),
    ]

    operations = [
    ]
