# Generated by Django 4.1.6 on 2024-11-28 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0004_alter_article_createdate_alter_article_startdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='year',
            field=models.ForeignKey(blank=True, default=61, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.schoolyear'),
        ),
    ]
