# Generated by Django 5.2.8 on 2025-11-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0004_add_scoresheet_ranking_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='numerical_answer2',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
