# Generated by Django 3.1.6 on 2022-02-26 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0006_auto_20220226_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='upload_time',
            field=models.DateTimeField(auto_created=True, auto_now_add=True),
        ),
    ]
