# Generated by Django 4.1.6 on 2026-04-27 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0006_add_problem_coordinators'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiad',
            name='is_problems_confidential',
            field=models.BooleanField(default=False),
        ),
    ]
