# Generated by Django 4.1.6 on 2024-12-17 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0006_remove_scoresheet_prizes_remove_scoresheet_ranking_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_a',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_b',
            field=models.IntegerField(default=0),
        ),
    ]
