# Generated by Django 3.1.6 on 2022-03-21 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220218_0750'),
        ('olympiad', '0007_auto_20220226_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='olympiad',
            options={'ordering': ['-school_year_id', '-id']},
        ),
        migrations.AddField(
            model_name='olympiad',
            name='next_round',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='olympiad.olympiad'),
        ),
        migrations.AlterField(
            model_name='award',
            name='place',
            field=models.CharField(choices=[('Алт', 'Алтан медаль'), ('Мөнгө', 'Мөнгөн медаль'), ('Хүрэл', 'Хүрэл медаль'), ('Тусгай', 'Тусгай шагнал'), ('Уран бодолт', 'Уран бодолт'), ('I шат', 'I шат'), ('II шат', 'II шат')], default='Алт', max_length=20),
        ),
        migrations.CreateModel(
            name='Threshold',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.IntegerField(default=7)),
                ('olympiad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='olympiad.olympiad')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.province')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.zone')),
            ],
        ),
    ]
