# Generated by Django 4.1.6 on 2024-12-17 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0007_scoresheet_ranking_a_scoresheet_ranking_b'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_a_p',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scoresheet',
            name='ranking_b_p',
            field=models.IntegerField(default=0),
        ),
    ]
