# Generated by Django 5.2.7 on 2026-08-12 07:19

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0008_fix_school_year_dates'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoundGuideline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField(choices=[(1, 'Сургуулийн олимпиад'), (2, 'Аймаг/Дүүргийн олимпиад'), (3, 'Бүс/УБ хотын олимпиад'), (4, 'Улсын олимпиад')])),
                ('title', models.CharField(max_length=200)),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('updatedate', models.DateField(auto_now=True, null=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympiad.schoolyear')),
            ],
            options={
                'ordering': ['round'],
                'unique_together': {('round', 'school_year')},
            },
        ),
    ]
