# Generated by Django 3.1.6 on 2022-03-25 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220218_0750'),
        ('olympiad', '0008_auto_20220321_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.author'),
        ),
    ]
