# Generated by Django 5.2.7 on 2026-08-12 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0009_roundguideline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundguideline',
            name='round',
            field=models.IntegerField(choices=[(1, 'Сургуулийн олимпиад'), (2, 'Аймаг/Дүүргийн олимпиад'), (3, 'Бүс/УБ хотын олимпиад'), (4, 'Улсын олимпиад'), (5, 'IMO сонгон шалгаруулалт'), (6, 'EGMO сонгон шалгаруулалт'), (7, 'APMO')]),
        ),
    ]
