# Generated by Django 4.1.6 on 2024-12-17 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0009_scoresheet_prize'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scoresheet',
            old_name='prize',
            new_name='prizes',
        ),
    ]
