# Generated by Django 3.1.6 on 2022-04-03 09:17

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0010_auto_20220403_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='Descr',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
