# Generated by Django 5.2.7 on 2026-08-18 07:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0011_fix_user_fk_cascade_constraints'),
        ('posts', '0005_fix_post_school_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolyear',
            name='guideline_post',
            field=models.ForeignKey(blank=True, help_text='Цэсний "Олимпиадын удирдамж" линк энэ хичээлийн жилд идэвхтэй үед энд заасан пост руу автоматаар холбогдоно.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guideline_school_years', to='posts.post', verbose_name='Олимпиадын удирдамж пост'),
        ),
    ]
