# Generated by Django 3.1.6 on 2022-04-04 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0011_auto_20220403_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='state',
            field=models.IntegerField(choices=[(0, 'Хариулаагүй'), (1, 'Засагдаагүй'), (2, 'Урьдчилсан'), (3, 'Маргаантай'), (4, 'Зөвшөөрөгдсөн'), (5, 'Батлагдсан')], default=0),
        ),
    ]
