# Generated by Django 5.2.7 on 2026-08-18 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_fix_user_fk_cascade_constraints'),
        ('olympiad', '0012_schoolyear_guideline_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='OlympiadTimeline',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Дугаар')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Эхэлсэн огноо')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дууссан огноо')),
                ('description', models.TextField(blank=True, default='', verbose_name='Тайлбар')),
                ('contestants', models.PositiveIntegerField(blank=True, null=True, verbose_name='Оролцогчдын тоо')),
                ('host', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.province', verbose_name='Байршил')),
                ('school_year', models.ForeignKey(blank=True, help_text='"Дүн" линк энд заасан хичээлийн жилээр шүүнэ.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.schoolyear', verbose_name='Хичээлийн жил')),
            ],
            options={
                'verbose_name': 'Олимпиадын түүхэн бичлэг',
                'verbose_name_plural': 'Олимпиадын түүх (timeline)',
                'ordering': ['-number'],
            },
        ),
    ]
