# Generated by Django 5.2.7 on 2026-08-18 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0013_olympiadtimeline'),
    ]

    operations = [
        migrations.AddField(
            model_name='olympiadtimeline',
            name='series_file_url',
            field=models.URLField(blank=True, help_text='Тухайн олимпиадын бодлого/хариултын цувралын PDF файлын холбоос.', null=True, verbose_name='Цуврал'),
        ),
    ]
