# Generated by Django 5.2.7 on 2026-08-18 12:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0014_olympiadtimeline_series_file_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='olympiadtimeline',
            name='school_year',
            field=models.ForeignKey(blank=True, help_text='Тухайн олимпиадтай холбоотой хичээлийн жил.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympiad.schoolyear', verbose_name='Хичээлийн жил'),
        ),
    ]
