# Generated by Django 3.1.6 on 2022-04-10 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220218_0750'),
        ('olympiad', '0015_remove_team_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='province',
        ),
        migrations.AddField(
            model_name='team',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='accounts.zone'),
        ),
    ]
