# Generated by Django 5.2.7 on 2026-10-06 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0015_alter_olympiadtimeline_school_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roundguideline',
            name='round',
            field=models.IntegerField(choices=[(1, 'Сургуулийн олимпиад'), (2, 'Аймаг/Дүүргийн олимпиад'), (3, 'Бүс/Нийслэлийн олимпиад'), (4, 'Улсын олимпиад'), (5, 'IMO сонгон шалгаруулалт'), (6, 'EGMO сонгон шалгаруулалт'), (7, 'APMO')]),
        ),
    ]
