# Generated by Django 3.1.6 on 2022-04-10 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20220218_0750'),
        ('olympiad', '0016_auto_20220411_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='accounts.province'),
        ),
    ]
