# Generated by Django 3.1.6 on 2022-04-11 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0017_team_province'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='place',
            new_name='ranking',
        ),
    ]
