# Generated by Django 3.1.6 on 2023-02-05 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympiad', '0020_result_source_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='numerical_answer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='result',
            name='answer',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
