# Generated by Django 3.1.6 on 2021-05-24 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_auto_20210414_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='quiz_type',
            field=models.IntegerField(choices=[(0, 'Тест'), (1, 'Шалгалт')], default=0),
        ),
    ]
