# Generated by Django 4.1.6 on 2024-11-14 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ЕБС', max_length=200)),
                ('is_sent_confirmation', models.BooleanField(default=False)),
                ('is_received_confirmation', models.BooleanField(default=False)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='auth.group')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='accounts.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
    ]
