# Generated by Django 5.2.8 on 2025-11-21 16:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedExcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='excel_uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ЕБС', max_length=200)),
                ('alias', models.CharField(blank=True, help_text='Сургуулийн өөр нэр, товчлол эсвэл нэмэлт хайлтын alias', max_length=1023, null=True)),
                ('is_sent_confirmation', models.BooleanField(default=False)),
                ('is_received_confirmation', models.BooleanField(default=False)),
                ('is_official_participation', models.BooleanField(default=False)),
                ('group', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='auth.group', verbose_name='Хамаарах бүлэг')),
                ('manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managing', to=settings.AUTH_USER_MODEL, verbose_name='Сургуулийн удирдлага/менежер')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='accounts.province')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='moderating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'group'), name='unique_user_group_combination')],
            },
        ),
    ]
