# Generated by Django 5.0.6 on 2024-09-21 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to='auth.group')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderators', to='accounts.province')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moderating', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'group')},
            },
        ),
        migrations.DeleteModel(
            name='Moderator',
        ),
    ]
