# Generated by Django 5.2.8 on 2025-11-24 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='official_levels',
            field=models.ManyToManyField(blank=True, related_name='official_schools', to='accounts.level', verbose_name='Албан ёсны оролцооны түвшингүүд'),
        ),
    ]
