# Generated by Django 5.0.6 on 2024-09-21 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0002_school_delete_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='name',
            field=models.CharField(default='ЕБС', max_length=200),
        ),
    ]
