# Generated by Django 4.1.6 on 2025-12-18 14:06
# Modified to handle cases where table already exists from 0002_add_official_levels

from django.db import migrations, models


def safe_add_official_levels_field(apps, schema_editor):
    """
    Safely add official_levels ManyToManyField.
    Checks if table already exists (from 0002_add_official_levels) before creating.
    This is a no-op migration that ensures Django's state matches the database.
    """
    from django.db import connection
    with connection.cursor() as cursor:
        # Get current schema
        cursor.execute("SELECT current_schema();")
        schema = cursor.fetchone()[0]

        # Check if the M2M table already exists
        cursor.execute("""
            SELECT EXISTS (
                SELECT FROM information_schema.tables
                WHERE table_schema = %s
                AND table_name = 'schools_school_official_levels'
            );
        """, [schema])
        table_exists = cursor.fetchone()[0]

        if table_exists:
            # Table already exists from migration 0002, this is just updating Django's state
            pass
        else:
            # Table doesn't exist - create it manually
            # This should match the structure created by Django's AddField
            cursor.execute("""
                CREATE TABLE schools_school_official_levels (
                    id SERIAL PRIMARY KEY,
                    school_id BIGINT NOT NULL REFERENCES schools_school(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    level_id INTEGER NOT NULL REFERENCES accounts_level(id) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED,
                    UNIQUE (school_id, level_id)
                );
            """)
            cursor.execute("""
                CREATE INDEX schools_school_official_levels_school_id_ac6da625
                ON schools_school_official_levels (school_id);
            """)
            cursor.execute("""
                CREATE INDEX schools_school_official_levels_level_id_d7249c1c
                ON schools_school_official_levels (level_id);
            """)


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_usermergerequest_confirmations_and_more'),
        ('schools', '0002_add_official_levels'),
    ]

    operations = [
        # Use RunPython to safely create the M2M table only if it doesn't exist
        migrations.RunPython(safe_add_official_levels_field, migrations.RunPython.noop),
        # Add field to Django state (table already created by RunPython above)
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # No database changes needed
            state_operations=[
                migrations.AddField(
                    model_name='school',
                    name='official_levels',
                    field=models.ManyToManyField(blank=True, related_name='official_schools', to='accounts.level', verbose_name='Албан ёсны оролцооны түвшингүүд'),
                ),
            ],
        ),
    ]
