# Generated by Django 5.2.7 on 2026-09-28 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0002_fix_user_fk_cascade_constraints'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='kind',
            field=models.CharField(choices=[('general', 'Заавар (сургуулийн ажилтнуудад)'), ('training', 'Олимпиадын бэлтгэлийн материал')], db_index=True, default='general', max_length=20, verbose_name='Төрөл'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='teachers',
            field=models.CharField(blank=True, default='', help_text='Таслалаар тусгаарлана. Жишээ нь: Б. Батбаясгалан, Т. Хулан', max_length=500, verbose_name='Хичээл заасан багш нар'),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='title',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Гарчиг'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
