# Generated by Django 5.2.7 on 2026-10-05 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file_management', '0003_fileupload_training_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='link',
            field=models.URLField(blank=True, default='', help_text='Google Drive, YouTube г.м. холбоос. Файл оруулахгүй бол заавал бөглөнө.', max_length=1000, verbose_name='Холбоос'),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='file',
            field=models.FileField(blank=True, upload_to='files/'),
        ),
    ]
